version: "3.9"
services:
  postgres-db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - bnet
    ports:
      - 5432:5432
  # Kjøre opp pgadmin i docker om man vil 
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_PASSWORD=password
  #     - PGADMIN_DEFAULT_EMAIL=post@gres.no
  #   networks:
  #     - bnet
  #   ports:
  #     - 81:80
  java-api:
    build:
      context: ./BulletinJavaApi
    environment:
      - DB_HOST=postgres-db
    networks:
      - bnet
    ports:
      - 8080:8080
  dotnet-api:
    build:
      context: ./BulletinDotnetApi
      dockerfile: ./BulletinDotnetApi/Dockerfile
    environment:
      - JavaApiBaseUrl=http://java-api:8080
      - AzureFunctionName=CleanMessage
      - AzureFunctionApiBasePath=http://az-func
    networks:
      - bnet
    ports:
      - 5232:80
  frontend:
    build:
      context: ./BulletinFrontend/
    environment:
      # Denne vil kjøre fra nettleser som da er hostmanskin, skal derfor ikke være http://dotnet-api
      - VITE_API_URL=http://localhost:5232
    networks:
      - bnet
    ports:
      - 5173:80
  az-func:
    build:
      context: ./AzureFunction
    networks:
      - bnet
    ports:
      - 82:80

networks:
  bnet: